# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pashiri.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pashiri.proto',
  package='pahiri_buffer',
  syntax='proto3',
  serialized_pb=_b('\n\rpashiri.proto\x12\rpahiri_buffer\"<\n\x0bPashiriInfo\x12\x15\n\rpashiri_index\x18\x01 \x01(\x05\x12\x16\n\x0epashiri_number\x18\x02 \x01(\x05\"P\n\x0fPashiriTaskInfo\x12\x10\n\x08\x65xchange\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0c\n\x04\x62\x61se\x18\x03 \x01(\t\x12\r\n\x05quote\x18\x04 \x01(\t2\\\n\x0ePashiriManager\x12J\n\nAssignTask\x12\x1a.pahiri_buffer.PashiriInfo\x1a\x1e.pahiri_buffer.PashiriTaskInfo\"\x00\x62\x06proto3')
)




_PASHIRIINFO = _descriptor.Descriptor(
  name='PashiriInfo',
  full_name='pahiri_buffer.PashiriInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pashiri_index', full_name='pahiri_buffer.PashiriInfo.pashiri_index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pashiri_number', full_name='pahiri_buffer.PashiriInfo.pashiri_number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=92,
)


_PASHIRITASKINFO = _descriptor.Descriptor(
  name='PashiriTaskInfo',
  full_name='pahiri_buffer.PashiriTaskInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange', full_name='pahiri_buffer.PashiriTaskInfo.exchange', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='pahiri_buffer.PashiriTaskInfo.symbol', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='base', full_name='pahiri_buffer.PashiriTaskInfo.base', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quote', full_name='pahiri_buffer.PashiriTaskInfo.quote', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=174,
)

DESCRIPTOR.message_types_by_name['PashiriInfo'] = _PASHIRIINFO
DESCRIPTOR.message_types_by_name['PashiriTaskInfo'] = _PASHIRITASKINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PashiriInfo = _reflection.GeneratedProtocolMessageType('PashiriInfo', (_message.Message,), dict(
  DESCRIPTOR = _PASHIRIINFO,
  __module__ = 'pashiri_pb2'
  # @@protoc_insertion_point(class_scope:pahiri_buffer.PashiriInfo)
  ))
_sym_db.RegisterMessage(PashiriInfo)

PashiriTaskInfo = _reflection.GeneratedProtocolMessageType('PashiriTaskInfo', (_message.Message,), dict(
  DESCRIPTOR = _PASHIRITASKINFO,
  __module__ = 'pashiri_pb2'
  # @@protoc_insertion_point(class_scope:pahiri_buffer.PashiriTaskInfo)
  ))
_sym_db.RegisterMessage(PashiriTaskInfo)



_PASHIRIMANAGER = _descriptor.ServiceDescriptor(
  name='PashiriManager',
  full_name='pahiri_buffer.PashiriManager',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=176,
  serialized_end=268,
  methods=[
  _descriptor.MethodDescriptor(
    name='AssignTask',
    full_name='pahiri_buffer.PashiriManager.AssignTask',
    index=0,
    containing_service=None,
    input_type=_PASHIRIINFO,
    output_type=_PASHIRITASKINFO,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PASHIRIMANAGER)

DESCRIPTOR.services_by_name['PashiriManager'] = _PASHIRIMANAGER

# @@protoc_insertion_point(module_scope)
