# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pashiri_pb2 as pashiri__pb2


class PashiriManagerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AssignTask = channel.unary_unary(
        '/pahiri_buffer.PashiriManager/AssignTask',
        request_serializer=pashiri__pb2.PashiriInfo.SerializeToString,
        response_deserializer=pashiri__pb2.PashiriTaskInfo.FromString,
        )


class PashiriManagerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AssignTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PashiriManagerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AssignTask': grpc.unary_unary_rpc_method_handler(
          servicer.AssignTask,
          request_deserializer=pashiri__pb2.PashiriInfo.FromString,
          response_serializer=pashiri__pb2.PashiriTaskInfo.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pahiri_buffer.PashiriManager', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
